services:
    wrangler:
        build:
            context: .
            dockerfile: Dockerfile-node
        volumes:
            - .:/app
            - ./package.json:/app/package.json
            - node_modules:/app/node_modules
        restart: unless-stopped
        ports:
            - 80:8787
        command: npm start
        # command: tail -f /dev/null #idle container
volumes:
    node_modules:
        