services:
    web:
        image: nginx:alpine
        volumes:
            - ./public_html:/usr/share/nginx/html
        ports:
            - "80:80"
        networks:
            - allegro
        restart: unless-stopped

networks:
    allegro:
        name: allegro